name: CI

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  XCODE_APP_NAME: Xcode_14.3.1.app

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: macos-13
    steps:
      - name: Checkout certificates
        uses: actions/checkout@v3
        with:
          repository: kamaal111/CodeSign
          ref: refs/heads/main
          token: ${{ secrets.CODE_SIGN_ACCESS_TOKEN }}

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Select Xcode version
        run: |
          ls -d /Applications/Xcode*
          sudo xcode-select --switch /Applications/$XCODE_APP_NAME/Contents/Developer

      - name: Import signing private key
        env:
          SIGNING_PRIVATE_KEY: SigningCertificates/Development/Apple Development Kamaal Farah (RH5CK7M348).p12
        run: just import-signing-private-key "${{ env.SIGNING_PRIVATE_KEY }}" "${{ secrets.DEVELOPMENT_SIGNING_CERTIFICATE_PASSWORD }}" "${{ secrets.KEYCHAIN_PASSPHRASE }}"

      - name: Checkout SelectCopy
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Bootstrap project
        run: just bootstrap

      - name: Format
        run: just format

      - name: Build
        run: just build
